### ISSUE TITLE
Initialize Project

### ISSUE THREAD

**Issue by forkball** [Team-Benedict/Scrambled-Eggs-Web#1]
Initialize the project to a state that it can be pulled down and started up by following repository documentation.

### Task Breakdown
 - [x] Follow the T3 project initialization using the [docs](https://create.t3.gg/en/introduction)
 - [x] Add Github templates
 - [x] Set up CiCd via Vercel
 - [x] Write a README explaining the project architecture and intent
 - [ ] Create a GitHub project for SEW
 - [x] Update GitHub issues/pr labels
